# Imports

In [1]:
from wordcloud import WordCloud
import matplotlib.pyplot as mat
import nltk
import os
import re
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from collections import Counter

# Télechargement des librairies NLTK

In [2]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     /home/lydie_15-03/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/lydie_15-03/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/lydie_15-03/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/lydie_15-03/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/lydie_15-03/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

### Fonction de traitement des dse mots

In [3]:
def bow(files):
    
    tokens = word_tokenize(files.lower())
    filte = [token for token in tokens if token not in stopwords.words('english') and token.isalpha()]

    lemmatiser = WordNetLemmatizer()

    lemmitazer = [lemmatiser.lemmatize(token) for token in filte]
    processed = Counter(lemmitazer)
    word_freq_df = pd.DataFrame(processed.items(), columns=['Word', 'Frequency'])
    frequency = word_freq_df.sort_values(by='Frequency', ascending=False)
    
    return frequency

### Boucle d'affichage des Bow

In [ ]:
for i in os.listdir("Text/"):
    with open(f'Text/{i}', 'r', encoding='utf-8') as file:
        files = file.read()
        name = i.replace('.txt', '')
        l = bow(files)
        display(name)
        display(l)

'Histories of two hundred and fifty-one divisions of the German army which participated in the wa'

              Word  Frequency
6         division       6410
290             re       2822
122       regiment       1934
272            rgt       1871
278           pion       1845
...            ...        ...
6004     determine          1
6006  solicitation          1
6007   prohibition          1
6008     accepting          1
6009   unsolicited          1

[6035 rows x 2 columns]

'The Last Leaf'

            Word  Frequency
122          one        262
114         time        202
26           men        179
624          man        177
172        great        176
...          ...        ...
8779   fairbanks          1
8764    obsolete          1
8765      exists          1
8766   financial          1
8767  assistance          1

[8820 rows x 2 columns]

'Peter-pan'

              Word  Frequency
2            peter        101
19         project         86
59           wendy         81
557           work         78
154            boy         74
...            ...        ...
1973    charitable          1
1974       uniform          1
1975     paperwork          1
1977  confirmation          1
1978          send          1

[2019 rows x 2 columns]

'The Progress of Invention in the Nineteenth'

              Word  Frequency
1961           fig        623
318        machine        596
128         patent        517
107          first        404
66    illustration        395
...            ...        ...
6584      xenophon          1
6579        armour          1
6578          popp          1
6577       shriver          1
6569           lug          1

[9879 rows x 2 columns]

'The fauna of the deep sea'

            Word  Frequency
149        water        216
71         depth        186
430       fathom        166
154         form        161
3          fauna        152
...          ...        ...
3631       arise          1
3632  alteration          1
3633    deletion          1
3634  synonymous          1
3635    readable          1

[3695 rows x 2 columns]

'The Rose and the Ring'

             Word  Frequency
119        giglio        249
61           king        189
180        prince        177
96            say        175
120         bulbo        128
...           ...        ...
2316        bosom          1
2317  exquisitely          1
2303      funeral          1
2304      satisfy          1
2260          ink          1

[3918 rows x 2 columns]

'Medieval People'

          Word  Frequency
310        one        237
208      great        205
237      house        174
204     thomas        166
403       work        165
...        ...        ...
9060      code          1
9065  disclaim          1
9067    remedy          1
9120  director          1
9121   gbnewby          1

[9149 rows x 2 columns]

'The Secret Garden'

            Word  Frequency
116         said        832
74          mary        696
52           one        460
914           th        373
324         like        369
...          ...        ...
4402   financial          1
4403  assistance          1
4404    reaching          1
4405        goal          1
4406    ensuring          1

[4482 rows x 2 columns]